images:
  cilium: quay.io/cilium/cilium:v1.13.10
  cilium-operator: quay.io/cilium/operator:v1.13.10
  istio-pilot: docker.io/istio/pilot:1.16.7
  istio-proxy: docker.io/istio/proxyv2:1.16.7
  vault: docker.io/hashicorp/vault:2.0.3
  vault-secrets-operator: ghcr.io/ricoberger/vault-secrets-operator:v1.26.0
