server:
  dev:
    enabled: true
  image:
    repository: ${IMAGE_VAULT_REPO}
    tag: ${IMAGE_VAULT_TAG}
  extraEnvironmentVars:
    VAULT_DEV_KV_V1: "true"
injector:
  enabled: false
ui:
  enabled: true
