image:
  repository: ${KINDTKS_REGISTRY}ghcr.io/ricoberger/vault-secrets-operator
  tag: v1.26.0
vault:
  address: http://vault.vault.svc:8200
  authMethod: token
environmentVars:
  - name: VAULT_TOKEN
    value: root
  - name: VAULT_TOKEN_LEASE_DURATION
    value: "0"
