ipam:
  mode: kubernetes
image:
  pullPolicy: IfNotPresent
  repository: ${IMAGE_CILIUM_REPO}
  tag: ${IMAGE_CILIUM_TAG}
  useDigest: false
operator:
  replicas: 1
  image:
    repository: ${IMAGE_CILIUM_OPERATOR_REPO}
    tag: ${IMAGE_CILIUM_OPERATOR_TAG}
    useDigest: false
preflight:
  image:
    repository: ${IMAGE_CILIUM_REPO}
    tag: ${IMAGE_CILIUM_TAG}
    useDigest: false
