image:
  repository: ${IMAGE_VAULT_SECRETS_OPERATOR_REPO}
  tag: ${IMAGE_VAULT_SECRETS_OPERATOR_TAG}
vault:
  address: http://vault.vault.svc:8200
  authMethod: token
environmentVars:
  - name: VAULT_TOKEN
    value: root
  - name: VAULT_TOKEN_LEASE_DURATION
    value: "0"
